"use client";
import Link from "next/link";
import { useEffect,useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
const steps=[
  ["01","Levantamiento","Medidas, niveles, apoyos, accesos y registro fotográfico del estado actual.",["Ubicación y uso","Medidas generales","Puntos eléctricos","Condiciones de montaje"]],
  ["02","Propuesta","Definición de estructura, cubierta, distribución, iluminación y sistema de accionamiento.",["Vista general","Materiales","Apertura fija o corrediza","Remates principales"]],
  ["03","Presupuesto y acuerdo","Alcance, materiales, condiciones de pago, plazo estimado y exclusiones documentadas.",["Cotización","Cronograma","Forma de pago","Condiciones de obra"]],
  ["04","Fabricación","Preparación de perfiles, piezas, acabados y componentes antes de ingresar al espacio.",["Corte y armado","Protección anticorrosiva","Pintura","Verificación de piezas"]],
  ["05","Instalación","Montaje de estructura, cubierta, iluminación y mecanismos según una secuencia definida.",["Protección del área","Nivel y alineación","Conexiones","Pruebas de apertura"]],
  ["06","Entrega","Revisión de funcionamiento, acabado, limpieza y conformidad del cliente.",["Prueba final","Observaciones","Recomendaciones de uso","Cierre documentado"]]
] as const;
export default function ProcesoPage(){const ref=useRef<HTMLElement>(null);useEffect(()=>{const root=ref.current;if(!root||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const ctx=gsap.context(()=>{gsap.fromTo(".process-line",{strokeDashoffset:1000},{strokeDashoffset:0,ease:"none",scrollTrigger:{trigger:root,start:"top 55%",end:"bottom 80%",scrub:true}});gsap.fromTo(".process-step",{opacity:0,y:28},{opacity:1,y:0,duration:.7,stagger:.08,scrollTrigger:{trigger:root,start:"top 72%",once:true}})},root);return()=>ctx.revert()},[]);return <main className="min-h-screen bg-[#07111d] pt-20 text-ca-text"><section className="border-b border-white/10 px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><span className="text-[10px] uppercase tracking-[.28em] text-brand-gold">Proceso de trabajo</span><h1 className="mt-6 max-w-5xl text-5xl font-display font-light uppercase leading-[.95] md:text-7xl">Medir, definir, fabricar, instalar y entregar.</h1></div><p className="text-sm leading-7 text-ca-text-secondary lg:col-span-4">Cada etapa reduce decisiones improvisadas y deja claros alcance, materiales, tiempos y responsables antes de avanzar.</p></div></section><section ref={ref} className="relative px-6 py-24 lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="relative lg:pl-24"><svg aria-hidden="true" viewBox="0 0 2 1000" preserveAspectRatio="none" className="absolute left-5 top-0 hidden h-full w-[2px] lg:block"><line x1="1" y1="0" x2="1" y2="1000" stroke="rgba(255,255,255,.12)" strokeWidth="2"/><path className="process-line" d="M1 0V1000" stroke="var(--color-brand-gold)" strokeWidth="2" fill="none" strokeDasharray="1000"/></svg><div className="grid gap-6">{steps.map(([n,title,text,details])=><article key={n} className="process-step grid gap-8 border-t border-white/10 py-10 lg:grid-cols-12"><div className="lg:col-span-2"><span className="font-mono text-sm text-brand-gold">{n}</span></div><div className="lg:col-span-5"><h2 className="text-3xl font-display font-light uppercase">{title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-ca-text-secondary">{text}</p></div><ul className="grid gap-3 text-sm text-ca-text-secondary lg:col-span-5">{details.map(item=><li key={item} className="border-b border-white/10 pb-3">{item}</li>)}</ul></article>)}</div></div><div className="mt-16 flex flex-wrap gap-6 border-t border-white/10 pt-8"><Link href="/contacto" className="inline-flex min-h-14 items-center bg-brand-gold px-7 text-[10px] font-semibold uppercase tracking-[.2em] text-[#07111d]">Solicitar evaluación</Link><Link href="/servicios" className="inline-flex min-h-14 items-center border border-white/15 px-7 text-[10px] uppercase tracking-[.2em]">Revisar servicios</Link></div></div></section></main>}
