"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {useEffect,useRef,useState} from "react";import {gsap} from "gsap";import {SunIcon,MoonIcon} from "./icons/AnimatedIcons";import {Logo} from "./Logo";import {BrandText} from "./BrandText";
const items=[["Inicio","/"],["Servicios","/servicios"],["Proyectos","/proyectos"],["Proceso","/proceso"],["Blog","/blog"],["Nosotros","/nosotros"],["Contacto","/contacto"]] as const;
export function Header(){const path=usePathname();const[open,setOpen]=useState(false);const[light,setLight]=useState(false);const[scrolled,setScrolled]=useState(false);const overlay=useRef<HTMLDivElement>(null);
useEffect(()=>{const saved=localStorage.getItem("casa-atenta-theme");const useLight=saved==="light"||(!saved&&matchMedia("(prefers-color-scheme: light)").matches);document.documentElement.classList.toggle("light",useLight);setLight(useLight)},[]);
useEffect(()=>{const onScroll=()=>setScrolled(scrollY>20);onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);
useEffect(()=>{setOpen(false)},[path]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
useEffect(()=>{const el=overlay.current;if(!el)return;document.body.style.overflow=open?"hidden":"";const ctx=gsap.context(()=>{if(open){gsap.to(el,{clipPath:"polygon(0 0,100% 0,100% 100%,0 100%)",duration:1,ease:"power4.inOut"});gsap.fromTo(".zenit-menu-link",{yPercent:120,opacity:0,rotate:3},{yPercent:0,opacity:1,rotate:0,duration:.9,stagger:.08,ease:"power4.out",delay:.3});gsap.fromTo(".zenit-menu-meta",{opacity:0,y:18},{opacity:1,y:0,duration:.7,delay:.65})}else{gsap.to(el,{clipPath:"polygon(0 0,100% 0,100% 0,0 0)",duration:.85,ease:"power4.inOut"})}},el);return()=>{ctx.revert();document.body.style.overflow=""}},[open]);
const toggleTheme=()=>{const next=!light;document.documentElement.classList.toggle("light",next);localStorage.setItem("casa-atenta-theme",next?"light":"dark");setLight(next)};
return <><header className={`fixed inset-x-0 top-0 z-50 px-6 transition-all duration-500 md:px-12 lg:px-24 ${scrolled?"border-b border-ca-border/30 bg-ca-glass-bg/90 py-4 shadow-[0_10px_40px_rgba(0,0,0,.18)] backdrop-blur-xl":"border-b border-transparent bg-transparent py-7"}`}><div className="mx-auto flex max-w-[1600px] items-center justify-between"><Link href="/" aria-label="Casa Atenta" className="relative z-[60] transition-transform duration-500 hover:scale-[1.03]"><Logo className="h-10 w-auto md:h-12 lg:h-14"/></Link><div className="relative z-[60] flex items-center gap-6 md:gap-10"><button onClick={toggleTheme} aria-label={light?"Usar tema oscuro":"Usar tema claro"} className="grid h-10 w-10 place-items-center rounded-full border border-ca-border bg-ca-glass-bg/30 backdrop-blur-md transition hover:border-brand-gold hover:text-brand-gold">{light?<MoonIcon size={16}/>:<SunIcon size={16}/>}</button><button onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="zenit-menu" className="group flex items-center gap-3"><span className="hidden font-mono text-xs uppercase tracking-[.2em] md:block">{open?"Cerrar":"Menú"}</span><span className="flex w-8 flex-col items-end gap-1.5"><i className={`block h-px bg-current transition-all duration-500 ${open?"w-8 translate-y-[3.5px] rotate-45":"w-8 group-hover:w-6"}`}/><i className={`block h-px bg-current transition-all duration-500 ${open?"w-8 -translate-y-[3.5px] -rotate-45":"w-5 group-hover:w-8"}`}/></span></button></div></div></header><div id="zenit-menu" ref={overlay} className="fixed inset-0 z-40 flex flex-col overflow-hidden bg-ca-bg-deep text-ca-text" style={{clipPath:"polygon(0 0,100% 0,100% 0,0 0)"}}><div className="grain-overlay opacity-[.05]"/><div className="architectural-grid absolute inset-0 opacity-20"/><div className="relative z-10 mx-auto flex h-full w-full max-w-[1600px] flex-col justify-center px-6 pb-12 pt-32 md:px-12 lg:px-24"><nav className="flex flex-col gap-4 md:gap-6">{items.map(([label,href],i)=><div key={href} className="overflow-hidden"><Link href={href} className="zenit-menu-link inline-flex items-baseline gap-5 font-display text-4xl font-light uppercase tracking-[.12em] transition hover:text-brand-gold md:text-5xl lg:text-6xl"><span className="font-mono text-[9px] tracking-[.2em] text-brand-gold">0{i+1}</span><BrandText>{label}</BrandText></Link></div>)}</nav><div className="zenit-menu-meta mt-auto flex flex-col gap-5 border-t border-ca-border/40 pt-7 font-mono text-[10px] uppercase tracking-[.18em] text-ca-text-secondary md:flex-row md:items-center md:justify-between"><span>Lima, Perú</span><a href="mailto:contacto@casa-atenta.com" className="transition hover:text-brand-gold">contacto@casa-atenta.com</a><span>Diseño · sombra · control</span></div></div></div></>}
export default Header;