"use client";
import {useEffect,useRef,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import {gsap} from "gsap";

const labels:Record<string,string>={"/":"Inicio","/servicios":"Servicios","/proyectos":"Proyectos","/proceso":"Proceso","/nosotros":"Nosotros","/contacto":"Contacto","/diseno":"Diseño","/soluciones":"Soluciones"};
const getLabel=(path:string)=>{const root="/"+path.split("/").filter(Boolean)[0];return labels[path]||labels[root]||"Casa Atenta"};

export function RouteExperience(){const router=useRouter();const pathname=usePathname();const overlay=useRef<HTMLDivElement>(null);const [label,setLabel]=useState(getLabel(pathname));const navigating=useRef(false);
useEffect(()=>{const root=overlay.current;const main=document.getElementById("main-content");if(!root||!main)return;setLabel(getLabel(pathname));navigating.current=false;window.scrollTo(0,0);if(matchMedia("(prefers-reduced-motion: reduce)").matches){gsap.set(root,{yPercent:-100});return}gsap.timeline().set(root,{yPercent:0}).to(root,{yPercent:-100,duration:.72,ease:"power4.inOut"}).fromTo(main,{opacity:.35,y:34},{opacity:1,y:0,duration:.72,ease:"power3.out"},"-=.48");},[pathname]);
useEffect(()=>{const click=(event:MouseEvent)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const anchor=(event.target as Element).closest("a");if(!anchor||anchor.target==="_blank"||anchor.hasAttribute("download"))return;const url=new URL(anchor.href,location.href);if(url.origin!==location.origin||url.pathname===pathname||url.hash)return;event.preventDefault();if(navigating.current)return;navigating.current=true;setLabel(getLabel(url.pathname));const root=overlay.current;if(!root||matchMedia("(prefers-reduced-motion: reduce)").matches){router.push(url.pathname+url.search);return}gsap.fromTo(root,{yPercent:100},{yPercent:0,duration:.62,ease:"power4.inOut",onComplete:()=>router.push(url.pathname+url.search)});};document.addEventListener("click",click);return()=>document.removeEventListener("click",click)},[pathname,router]);
return <div ref={overlay} aria-hidden="true" className="pointer-events-none fixed inset-0 z-[9000] translate-y-full overflow-hidden bg-[#07111d]"><div className="absolute inset-0 architectural-grid opacity-20"/><svg viewBox="0 0 1200 800" className="absolute inset-0 h-full w-full fill-none stroke-brand-gold/25"><path d="M80 650L360 300H840L1120 650"/><path d="M360 300V650M840 300V650"/><g strokeDasharray="8 12">{[420,480,540,600,660,720,780].map(x=><line key={x} x1={x} y1="300" x2={x} y2="650"/>)}</g></svg><div className="absolute inset-0 grid place-items-center"><div className="text-center"><span className="text-[9px] uppercase tracking-[.35em] text-brand-gold">Casa Atenta / navegación</span><p className="mt-5 text-4xl font-display font-light uppercase md:text-6xl">{label}</p><div className="mx-auto mt-6 h-px w-28 origin-left bg-brand-gold"/></div></div></div>}
export default RouteExperience;